# This is a basic workflow to help you get started with Actions

name: TestCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
     
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!dev'   # excludes dev
  
env:
 
 DOCKER_PASSWORD: ${{ secrets.TOKEN }} 
 #HOST: ${{ secrets.SERVER_IP }}
 #USERNAME: ${{ secrets.SERVER_USERNAME }}
 #PASSWORD: ${{ secrets.SERVER_PASSWORD }}
 #DEV_DB_USER_NAME: ${{ secrets.DEV_DB_USER_NAME }}
 #DEV_DB_NAME: ${{ secrets.DEV_DB_NAME }}
 #DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
 #DEV_DB_HOST: ${{ secrets.DEV_DB_HOST }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


 
  build: 
    
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to ghcr
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: 3-Hydroxytyramine
          password: $DOCKER_PASSWORD
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DPIdemo/Dockerfile
          push: true
          tags: ghcr.io/3-Hydroxytyramine/dpidemo:latest
          
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      
        
  #deploy:
    #needs: [build]
    #runs-on: ubuntu-latest
    #steps:
      
    #- name: Push to server
      #uses: appleboy/ssh-action@master
      #with:
         #host: $HOST
         #username: $USERNAME
         #password: $PASSWORD
         #port: 22
         #script: docker run 

    
      
        
    
